apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-environments
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.envMap }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end -}}
  {{- end }}