apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.application.service.type }}
  ports:
    - port: {{ .Values.application.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    io.letout.id: application
    {{- include "laravel.selectorLabels" . | nindent 4 }}
